### ISSUE TITLE
Depencancy issue node-expat -> nan

### ISSUE THREAD

**Issue by ComLock** [buglabs/node-xml2json#109]
Old versions of "nan" seems to be gone (from webjars at least).

Please upgrade node-expat to get newer existing version:
https://github.com/astro/node-expat/blob/master/package.json#L23

Here's the error message:
```
org.webjars.npm:xml2json:0.8.2 > org.webjars.npm:node-expat:2.3.7
> Could not find any version that matches org.webjars.npm:nan:[1.7.0,1.8).
```

**Comment by c4milo** [comment]
This should be fixed in the latest version. Please feel free to re-open if you keep seeing the issue.
