### ISSUE TITLE
npm install xml2json fail on Mac 

### ISSUE THREAD

**Issue by bugall** [buglabs/node-xml2json#110]
npm install xml2json
-
> node-expat@2.3.13 install /Users/ououufo/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_expat.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ououufo/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "xml2json"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ououufo/npm-debug.log

**Comment by c4milo** [comment]
Are you still seeing this error with the latest version?

**Comment by pibouu** [comment]
Hi,

I'm having the same issue too. I'm trying to install the latest version 0.9.1 but it does not work.

I looked up this error "ld: library not found for -lgcc_s.10.5" but I didn't find something useful.

I suspect it's because I'm on Yosemite. My co-workers are on El Capitain and it works for them. I will update to El Capitain and keep you inform.

(I'm using nvm 0.31.1 with nodejs 4.4.5 and npm 2.15.5)

**Comment by pibouu** [comment]
So I upgraded to El capitan (I recommand [this tutorial](https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/) if you didn't upgraded yet) and it worked !
With El capitan, you can upgrade to xcode 7.3.1 and I was on 6.3.x !

Hope it will work for you too !

**Comment by HoosierMike** [comment]
The node-expat bug is on windows too, no solution, cannot use this library with the new versions of node

**Comment by c4milo** [comment]
I just tested the latest version in NPM and it works fine Node v5.12.0 on El Capitán 

![](https://cldup.com/cmUMYL7XA7.png)

**Comment by c4milo** [comment]
I also tested with Node v4.4.7 LTS: 

![](https://cldup.com/sYM9zziI5d.png)

**Comment by c4milo** [comment]
I'm going to close this issue. Please open a new one for windows if you still this problem.
