### ISSUE TITLE
toXml() doesn't function as expected

### ISSUE THREAD

**Issue by rajivramv** [buglabs/node-xml2json#116]
I am not able to get the xml string as mentioned in the sample `toXml()` call in the README. Here is the Tonic [link](https://tonicdev.com/5730216ff32f571200898c36/5730216ff32f571200898c37).

**Comment by c4milo** [comment]
Fixed in https://github.com/buglabs/node-xml2json/commit/712cc3c7c7360e4318ffa337a41e066c1032d4cd
