### ISSUE TITLE
I wonder if xml2json supports xml namespace parsing

### ISSUE THREAD

**Issue by LycenYao** [buglabs/node-xml2json#120]
Sometimes there are some XML, having xmlns attributes. When I use xml2json to parse them, the output json will be in this form
{
    "namespace:key" : value
}

This make node.js programming difficult sometimes.
So I wonder if xml2json supports xml namespace parsing or not. Thank you.

**Comment by c4milo** [comment]
It does not support namespaces. I'm sorry.
