### ISSUE TITLE
something wrong --windows,    how can I solve this problem??  I have installed python

### ISSUE THREAD

**Issue by freya0608** [buglabs/node-xml2json#123]
$ npm install xml2json

> node-expat@2.3.15 install F:\web\node_modules\node-expat
> node-gyp rebuild

F:\web\node_modules\node-expat>if not defined npm_config_node_gyp (node "G:\install\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (G:\install\node\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at G:\install\node\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\\install\\node\\node.exe" "G:\\install\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\web\node_modules\node-expat
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'F:\web\package.json'
npm WARN web No description
npm WARN web No repository field.
npm WARN web No README data
npm WARN web No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\install\\node\\node.exe" "G:\\install\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "xml2json"
npm ERR! node v4.2.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\web\weather\npm-debug.log

**Comment by c4milo** [comment]
Please try: https://github.com/buglabs/node-xml2json/issues/121#issuecomment-239590028
