### ISSUE TITLE
sanitize option fails

### ISSUE THREAD

**Issue by ylh888** [buglabs/node-xml2json#52]
in the sanitize function, it appears that
(1) there is re-substitution of '#' 
(2) some missed substitution at end of string

test str = '&&<>()#&<>()#'
result = '&amp;&&lt;&gt;&&#35;40;&#41;#&<>()#'
should have been = '&amp;&amp;&lt;&gt;&#40;&#41;&#35;&amp;&lt;&gt;&#40;&#41;&#35;'

**Comment by c4milo** [comment]
@ylh888 thanks for your report! there was actually an issue in the sanitize function but it is not the one you pointed out. Details about the change can be found in the commit message.
