### ISSUE TITLE
'&' in XML not being sanitized, instead throws error

### ISSUE THREAD

**Issue by sethlesky** [buglabs/node-xml2json#59]
It seems that '&' isn't being sanitized and replaced with the expected '&amp;'. I've also tried passing explicitly turning on sanitization in the options parameter to no effect.

> var xml = '<yoo> & </yoo>';
> console.log(parser.toJson(xml));
Error: There are errors in your xml file: not well-formed (invalid token)
    at Object.module.exports [as toJson] (./xml2json/lib/xml2json.js:185:15)

**Comment by c4milo** [comment]
@sethlesky yes, because the XML is invalid, the error is being thrown by expat, the XML parser. Here is a working example: 

```javascript
var parser = require("xml2json")
var test = "<foo>&amp;</foo>"
var result = parser.toJson(test, {reversible: true});
console.log(result);

var result2 = parser.toXml(result);
console.log(result2)
```
