### ISSUE TITLE
Please don't rely on node-expat

### ISSUE THREAD

**Issue by SunboX** [buglabs/node-xml2json#65]
node-expat uses Python and won't compile on Windows. So node-xml2json won't work on Windows. And all packages relying on node-xml2json won't work on Windows (like node wsdl2.js). So please (please) don't rely on node-expat

**Comment by noveens** [comment]
Just saying: https://www.npmjs.com/package/xml-js is a pure JS library, and works with browserify as well.

@JasonGhent @RangerMauve
