### ISSUE TITLE
Spacing before and/or after special characters like &amp; is being stripped out

### ISSUE THREAD

**Issue by JasonTowner** [buglabs/node-xml2json#69]
Elements which contain ampersands aren't being consistently evaluated. The spacing before and/or after the ampersand is being removed.

Example data: 
```xml
<element>foo &amp; bar</element>
```
Results in: 
```"foo&bar"``` without the spaces,  instead of ```"foo & bar"```

**Comment by c4milo** [comment]
@JasonTowner sorry it took me so long to fix this issue. I will be publishing a new version in NPM soon.
