### ISSUE TITLE
npm install xml2json failed on mac-OSx with node.js v0.12

### ISSUE THREAD

**Issue by smartmouse** [buglabs/node-xml2json#77]
fama:nodejs-push-notification-server user$ npm install xml2json
-
> node-expat@2.0.0 install /home/users/user/nodejs-push-notification-server/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:54:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/home/ivyho/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:99:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Parse(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:171:42: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> SetEncoding(const Arguments& args)
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/home/ivyho/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:198:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetError(const Arguments& args)
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:212:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Stop(const Arguments& args)
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:229:37: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Resume(const Arguments& args)
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:244:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Reset(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:272:51: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentLineNumber(const Arguments& args)
                                                  ^~~~~~~~~
                                                  v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:285:53: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentColumnNumber(const Arguments& args)
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:298:50: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentByteIndex(const Arguments& args)
                                                 ^~~~~~~~~
                                                 v8::internal::Arguments
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:22:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../node-expat.cc:37:25: error: no member named 'NewSymbol' in 'v8::String';
      did you mean 'IsSymbol'?
    target->Set(String::NewSymbol("Parser"), t->GetFunction());
                ~~~~~~~~^~~~~~~~~
                        IsSymbol
/home/user/.node-gyp/0.12.0/deps/v8/include/v8.h:1379:8: note: 'IsSymbol'
      declared here
  bool IsSymbol() const;
       ^
../node-expat.cc:37:25: error: call to non-static member function without an
      object argument
    target->Set(String::NewSymbol("Parser"), t->GetFunction());
                ~~~~~~~~^~~~~~~~~
../node-expat.cc:39:24: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_startElement = NODE_PSYMBOL("startElement");
                       ^
../node-expat.cc:40:22: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_endElement = NODE_PSYMBOL("endElement");
                     ^
../node-expat.cc:41:22: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_startCdata = NODE_PSYMBOL("startCdata");
                     ^
../node-expat.cc:42:20: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_endCdata = NODE_PSYMBOL("endCdata");
                   ^
../node-expat.cc:43:16: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_text = NODE_PSYMBOL("text");
               ^
../node-expat.cc:44:33: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_processingInstruction = NODE_PSYMBOL("processingInstruction");
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/ivyho/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/home/SVT32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/users/nodejs-push-notification-server/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 12.5.0
npm ERR! argv "/home/SVT32/bin/node" "/home/SVT32/bin/npm" "install" "xml2json"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/nodejs-push-notification-server/npm-debug.l

**Comment by c4milo** [comment]
@smartmouse nodejs version?

**Comment by c4milo** [comment]
We are using node-expat 2.3.6 which should compile in node 0.12.x just fine.

**Comment by Dredalious** [comment]
I'm seeing this as well, both on my mac and our build server (ubuntu). Both running Node v0.12.2 with xml2json 0.6.1

**Comment by c4milo** [comment]
That is odd. This is my output when installing in Linux. It only has warnings and compiles just fine: 

```
vagrant@inotify:/tmp$ npm install xml2json
\
> node-expat@2.3.7 install /tmp/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/xml2json/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc: In static member function ‘static void Parser::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../node-expat.cc:42:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
         ^
../node-expat.cc:42:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
                                                                ^
../node-expat.cc: In static member function ‘static void Parser::SetEncoding(const v8::FunctionCallbackInfo<v8::Value>&)’:
../node-expat.cc:150:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
         ^
../node-expat.cc:150:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
                                                                ^
../node-expat.cc: In static member function ‘static void Parser::Reset(const v8::FunctionCallbackInfo<v8::Value>&)’:
../node-expat.cc:223:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
         ^
../node-expat.cc:223:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2110) [-Wdeprecated-declarations]
         NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
                                                                ^
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  SOLINK_MODULE(target) Release/obj.target/node_expat.node: Finished
  COPY Release/node_expat.node
make: Leaving directory `/tmp/node_modules/xml2json/node_modules/node-expat/build'
xml2json@0.6.2 node_modules/xml2json
└── node-expat@2.3.7 (bindings@1.2.1, nan@1.7.0, debug@2.1.3)
```

**Comment by Dredalious** [comment]
Sorry, forgot to reply back...
We found the culprit, we were running npm install with node v0.12, but when running the application we were using node v0.11, so that was off course the problem.
Strangely enough this was the only problem we encountered. We reverted everything back to v0.11 and now all is fine again.

because of the warnings we thought it was an issue with the lib

**Comment by c4milo** [comment]
@Dredalious Nice! I'm glad you guys solved your issue. Thanks for letting me know.

**Comment by macgera** [comment]
Same problem now. With npm 0.12.7. Try everything, nothing works... :(

**Comment by c4milo** [comment]
@macgera what do you mean? This is not an issue in node-xml2json as @Dredalious pointed out.

**Comment by szkrd** [comment]
This has surfaced for me now on High Sierra and I really don't have a clue, not even hours of googling (everything worked fine on Arch linux). Xcode is up to date, node is 10.6, npm is 6.1, everything else compiles fine, except for expat here. Any ideas?
