### ISSUE TITLE
String with numbers is being truncated

### ISSUE THREAD

**Issue by 0505gonzalez** [buglabs/node-xml2json#92]
`<example>17.500</example>`
Gets converted to
`example: 17.5`

**Comment by LopezCatherine** [comment]
What options were you passing to the xml2json functions? do you have coerce enabled?

**Comment by 0505gonzalez** [comment]
I wasn't overriding the options, thanks for the reply, it works

**Comment by c4milo** [comment]
Yeah, coerce doesn't really support internationalization so it will consider `17.500` as `17.5` and will remove trailing zeros. Disabling coercion fixes the problem as @LopezCatherine pointed out.
