### ISSUE TITLE
README.md refers to node-expat documentation which gets a 404 error

### ISSUE THREAD

**Issue by vielmetti** [buglabs/node-xml2json#99]
From README.md

>  This module uses node-expat which will require extra steps if you want to get it installed on Windows. Please refer to its documentation.

The link goes to http://node-xmpp.org/doc/expat.html#installing-on-windows? which gives a 404 Not Found error.

I'll note that the node-expat issues on https://github.com/node-xmpp/node-expat/issues include several people describing issues with Windows installs; the README should reflect current expectations about Windows related installations in some more detail.

**Comment by vielmetti** [comment]
thanks!

**Comment by c4milo** [comment]
@vielmetti no, thanks to you for letting me know about that :)

**Comment by c4milo** [comment]
Oops, will fix it ASAP, thanks!

**Comment by c4milo** [comment]
@OmgImAlexis, it should be fixed now. Thanks!
